The ``0-add_integer`` module
======================

Using ``add_integer``
-------------------

Retrieve function from module:
	>>> add_integer = __import__("0-add_integer").add_integer

Verify for module docstring:
	 >>> n = __import__("0-add_integer").__doc__
	 >>> len(n) > 1
	 True

Verify for function docstring:
	 >>> l = __import__("0-add_integer").add_integer.__doc__
         >>> len(l) > 1
         True

Verify addition:
	 >>> add_integer(2, 4)
	 6

Verify positive with negative:
	 >>> add_integer(3, -6)
	 -3

Verify negative with positive:
	 >>> add_integer(-9, 6)
	 3

Verify addition over multiple values:
	 >>> [add_integer(a, a ** 2) for a in range(5)]
	 [0, 2, 6, 12, 20]

Verify float with integer:
	 >>> add_integer(3.1, 5)
	 8

Verify integer with float:
	 >>> add_integer(4, 6.5)
	 10

Verify add two float:
	 >>> add_integer(5.5, 4.1)
	 9

Verify for passed NaN:
	 >>> add_integer(2, float('nan'))
	 Traceback (most recent call last):
	 ...
	 ValueError: can't convert float NaN to int

Verify for passed inf:
	 >>> add_integer(2, float('inf'))
	 Traceback (most recent call last):
	 ...
	 OverflowError: can't convert float to int

Verify long long int:
	 >>> add_integer(999999999999999999999999999999, 1)
	 1000000000000000000000000000000

Verify non-int with number:
	 >>> add_integer([2], 3)
	 Traceback (most recent call last):
	 ...
	 TypeError: a must be an integer

Verify number with non-int:
	 >>> add_integer(4, "1")
	 Traceback (most recent call last):
	 ...
	 TypeError: b must be an integer

Verify non-int with non-int:
	 >>> add_integer((3,), {"key": "value"})
         Traceback (most recent call last):
         ...
         TypeError: a must be an integer

Verify bool with int:
	 >>> add_integer(True, 2)
	 Traceback (most recent call last):
         ...
         TypeError: a must be an integer

Verify int with bool:
	 >>> add_integer(1, False)
         Traceback (most recent call last):
         ...
         TypeError: b must be an integer

Verify no arguments:
	 >>> add_integer()
	 Traceback (most recent call last):
	 ...
	 TypeError: add_integer() missing 2 required args: 'a' and 'b'

Verify one argument:
	 >>> add_integer(2)
	 Traceback (most recent call last):
         ...
	 TypeError: add_integer() missing 1 required  argt: 'b'

Verify more than two arguments:
	 >>> add_integer(2, 3, 4)
         Traceback (most recent call last):
         ...
         TypeError: add_integer() takes two arguments but three were give
